[package]
name = "plasma-night-colorscheme-switcher"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.34"
dotenv = "0.15.0"
sunrise = "1.0.1"
tokio = { version = "1.36.0", features = ["process", "time", "macros", "rt", "rt-multi-thread"], default-features = false }
